### ISSUE TITLE
chapter8: @font-face rule issue

### ISSUE THREAD

**Issue by nikkohijo** [bethrobson/Head-First-HTML#4]
In chapter 8, page 325, the code doesn't seem to work.

```
@font-face {
  font-family: "Emblema One";
  src: url("http://wickedlysmart.com/hfhtmlcss/chapter8/journal/EmblemaOne-Regular.woff"),
       url("http://wickedlysmart.com/hfhtmlcss/chapter8/journal/EmblemaOne-Regular.ttf");
}
```

but altering it to this, does.

```
@font-face {
	font-family: "Emblema One";
	src: url("EmblemaOne-Regular.woff") format("woff");
}
```

**Comment by Vjacheslav74** [comment]
The same

**Comment by ckloudy** [comment]
Neither of these options are working for me. Do I have to save the file on my system for this to work?

Edit: Found a work around using @import as it isn't very clear what you are supposed to do here, IMO.

**Comment by bethrobson** [comment]
Hey there, yes please save the font files on your local machines and change the URLs to a relative path to the fonts! See code in chapter8. https://github.com/bethrobson/Head-First-HTML/blob/master/chapter8/journal/journal.css
